name: 🎉 Release Binary

on:
  push:
    tags:
      - v*
jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v3
        with: 
          fetch-depth: 0   
      - 
        name: Set up Go
        uses: actions/setup-go@v3
        with:
          check-latest: true
          go-version: '>=1.19.0'
      - 
        name: run goreleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          args: "release --clean"
          version: latest
          workdir: v2/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
